/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/grocery/households": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listHouseholds"];
    put?: never;
    post: operations["createHousehold"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/households/{id}/invites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createInvite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/invites/{code}/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["joinHousehold"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/lists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listLists"];
    put?: never;
    post: operations["createList"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/lists/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateList"];
    trace?: never;
  };
  "/api/grocery/lists/{id}/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["addItems"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/lists/{id}/items/{itemId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteItem"];
    options?: never;
    head?: never;
    patch: operations["updateItem"];
    trace?: never;
  };
  "/api/grocery/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listRecipes"];
    put?: never;
    post: operations["createRecipe"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/recipes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getRecipe"];
    put: operations["updateRecipe"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/pantry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPantry"];
    put?: never;
    post: operations["addPantryItems"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/pantry/remove": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["removePantryItems"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/pantry/quantity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["setPantryItemQuantity"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/equipment": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getEquipment"];
    put?: never;
    post: operations["addEquipment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/equipment/remove": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["removeEquipment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getOrders"];
    put?: never;
    post: operations["recordOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/preferred-store": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPreferredStore"];
    put: operations["setPreferredStore"];
    post?: never;
    delete: operations["deletePreferredStore"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/grocery/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getShoppingProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: string;
    };
    Household: {
      id: string;
      name: string;
      role: string;
      created_by: string;
      /** Format: int64 */
      created_at: number;
    };
    Invite: {
      code: string;
      household_id: string;
      created_by: string;
      /** Format: int64 */
      expires_at: number;
      max_uses: number;
      used_count: number;
    };
    List: {
      id: string;
      household_id: string | null;
      owner_user_id: string;
      title: string;
      status: string;
      /** Format: int64 */
      artifact_version?: number;
      /** Format: int64 */
      created_at: number;
      /** Format: int64 */
      updated_at: number;
      items: components["schemas"]["Item"][];
    };
    Item: {
      id: string;
      list_id: string;
      name: string;
      quantity: string;
      note: string | null;
      upc?: string | null;
      position: number;
      added_by: string;
      checked_by: string | null;
      /** Format: int64 */
      checked_at: number | null;
      /** Format: int64 */
      updated_at: number;
    };
    NewItem: {
      name: string;
      quantity?: string;
      note?: string | null;
      upc?: string | null;
    };
    ItemPatch: {
      name?: string | null;
      quantity?: string | null;
      note?: string | null;
      checked?: boolean | null;
    };
    ListPatch: {
      title?: string | null;
      status?: string | null;
    };
    Recipe: {
      id: string;
      household_id: string | null;
      owner_user_id: string;
      title: string;
      description: string;
      servings: string;
      notes: string;
      status: string;
      /** Format: int64 */
      artifact_version?: number;
      /** Format: int64 */
      created_at: number;
      /** Format: int64 */
      updated_at: number;
      ingredients: components["schemas"]["Ingredient"][];
      steps: components["schemas"]["RecipeStep"][];
      tags: string[];
    };
    Ingredient: {
      id: string;
      recipe_id: string;
      name: string;
      quantity: string;
      unit: string;
      note: string;
      position: number;
    };
    RecipeStep: {
      id: string;
      recipe_id: string;
      instruction: string;
      position: number;
    };
    NewIngredient: {
      name: string;
      quantity?: string;
      unit?: string;
      note?: string;
    };
    RecipeContent: {
      title: string;
      description?: string;
      servings?: string;
      notes?: string;
      ingredients: components["schemas"]["NewIngredient"][];
      steps: string[];
      tags?: string[];
    };
    SavedRecipeInput: {
      household_id?: string | null;
      title: string;
      description?: string;
      servings?: string;
      notes?: string;
      ingredients: components["schemas"]["NewIngredient"][];
      steps: string[];
      tags?: string[];
    };
    PantryItem: {
      name: string;
      /** Format: double */
      quantity: number;
      /** Format: int64 */
      added_at: number;
      /** Format: int64 */
      expires_at?: number | null;
    };
    EquipmentItem: {
      name: string;
      category?: string | null;
      /** Format: int64 */
      added_at: number;
    };
    OrderItem: {
      upc: string;
      name: string;
      quantity: number;
      /** Format: double */
      price?: number | null;
    };
    Order: {
      id: string;
      items: components["schemas"]["OrderItem"][];
      total_items: number;
      /** Format: double */
      estimated_total?: number | null;
      /** Format: int64 */
      placed_at: number;
      location_id?: string | null;
      notes?: string | null;
    };
    RecordOrderInput: {
      id?: string;
      items: components["schemas"]["OrderItem"][];
      total_items: number;
      /** Format: double */
      estimated_total?: number | null;
      /** Format: int64 */
      placed_at: number;
      location_id?: string | null;
      notes?: string | null;
    };
    PreferredStore: {
      location_id: string;
      name: string;
      address: string;
      chain: string;
      /** Format: int64 */
      set_at: number;
    };
    PreferredStoreInput: {
      location_id: string;
      name: string;
      address: string;
      chain: string;
      /** Format: int64 */
      set_at?: number;
    };
    FrequentItem: {
      name: string;
      upc: string;
      orders: number;
      total_quantity: number;
    };
    ShoppingProfile: {
      preferred_store?: components["schemas"]["PreferredStore"];
      pantry: components["schemas"]["PantryItem"][];
      equipment: components["schemas"]["EquipmentItem"][];
      recent_orders: components["schemas"]["Order"][];
      frequent_items: components["schemas"]["FrequentItem"][];
    };
  };
  responses: {
    /** @description Structured grocery API error */
    GroceryError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listHouseholds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Households available to the shopper */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Household"][];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  createHousehold: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name: string;
        };
      };
    };
    responses: {
      /** @description Household created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Household"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  createInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          max_uses?: number;
        };
      };
    };
    responses: {
      /** @description Household invite created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Invite"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  joinHousehold: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Household joined */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Household"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  listLists: {
    parameters: {
      query?: {
        householdId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grocery lists available to the shopper */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["List"][];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  createList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          household_id?: string | null;
          title: string;
          items?: components["schemas"]["NewItem"][];
        };
      };
    };
    responses: {
      /** @description Grocery list created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["List"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  getList: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grocery list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["List"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  updateList: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListPatch"];
      };
    };
    responses: {
      /** @description Grocery list updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["List"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  addItems: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          items: components["schemas"]["NewItem"][];
        };
      };
    };
    responses: {
      /** @description Grocery list items added */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Item"][];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  deleteItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grocery list item deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["GroceryError"];
    };
  };
  updateItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemPatch"];
      };
    };
    responses: {
      /** @description Grocery list item updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Item"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  listRecipes: {
    parameters: {
      query?: {
        householdId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recipes available to the shopper */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipe"][];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  createRecipe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavedRecipeInput"];
      };
    };
    responses: {
      /** @description Recipe created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipe"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  getRecipe: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recipe */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipe"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  updateRecipe: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeContent"];
      };
    };
    responses: {
      /** @description Recipe updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipe"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  getPantry: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pantry items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["PantryItem"][];
          };
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  addPantryItems: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          items: {
            name: string;
            /** Format: double */
            quantity?: number;
            /** Format: int64 */
            expires_at?: number;
          }[];
        };
      };
    };
    responses: {
      /** @description Updated pantry items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["PantryItem"][];
          };
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  removePantryItems: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          names?: string[];
          all?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated pantry items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["PantryItem"][];
          };
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  setPantryItemQuantity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name: string;
          /** Format: double */
          quantity: number;
        };
      };
    };
    responses: {
      /** @description Updated pantry items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["PantryItem"][];
          };
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  getEquipment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Kitchen equipment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["EquipmentItem"][];
          };
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  addEquipment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          items: {
            name: string;
            category?: string;
          }[];
        };
      };
    };
    responses: {
      /** @description Updated kitchen equipment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["EquipmentItem"][];
          };
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  removeEquipment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          names?: string[];
          all?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated kitchen equipment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items: components["schemas"]["EquipmentItem"][];
          };
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  getOrders: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recent shopping orders */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            orders: components["schemas"]["Order"][];
          };
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  recordOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordOrderInput"];
      };
    };
    responses: {
      /** @description Shopping order recorded */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  getPreferredStore: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Preferred store */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreferredStore"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  setPreferredStore: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreferredStoreInput"];
      };
    };
    responses: {
      /** @description Preferred store updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreferredStore"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
  deletePreferredStore: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Preferred store deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["GroceryError"];
    };
  };
  getShoppingProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Shopping profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShoppingProfile"];
        };
      };
      default: components["responses"]["GroceryError"];
    };
  };
}
