minimumReleaseAge: 0

allowBuilds:
  "@clerk/shared": true
  "@sentry/cli": false
  "@scarf/scarf": false
  bufferutil: true
  browser-tabs-lock: false
  core-js: true
  "core-js-pure": true
  esbuild: true
  "utf-8-validate": true
  unrs-resolver: false

patchedDependencies:
  "@clerk/expo@4.6.8": patches/@clerk__expo@4.6.8.patch
