packages:
  - "packages/*"

minimumReleaseAge: 0

syncInjectedDepsAfterScripts:
  - fmt

allowBuilds:
  "@clerk/shared": true
  "@sentry/cli": false
  "@scarf/scarf": false
  bufferutil: true
  browser-tabs-lock: false
  core-js: true
  "core-js-pure": true
  esbuild: true
  "utf-8-validate": true

patchedDependencies:
  "@expo/ui@57.0.18": patches/@expo__ui@57.0.18.patch
